---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: http4s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: Always
        command:
           - "sh"
           - "-c"
           - "while true; do echo $(date); sleep 1; done"

