apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http4s
  namespace: http4s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: http4s
        image: aterefe/http4s:HEAD-222a3ac
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
