apiVersion: v1
kind: Service
metadata:
  name: http4s
  namespace: http4s
spec:
  selector:
    app: master
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 9000
    targetPort: 9000
